spring.application.name=day27l
spring.data.mongodb.uri = mongodb://localhost:27017/todos
# spring.data.mongodb.uri = mongodb://localhost:27017/boardgame
# spring.data.mongodb.uri=mongodb+srv://cluster0.rh28y.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
# spring.data.mongodb.username=fred
# spring.data.mongodb.password=abc123
# spring.data.mongodb.database=boardgames