package vttp_paf_day24l.vttp_paf_day24l.model;

public class ReservationDetail {
    
    // autogenerated
    private int id;
    // must be a valid book record
    private Book book;
    private Reservation reservation;

    public ReservationDetail() {

    }

    

    public ReservationDetail(int id, Book book, Reservation reservation) {
        this.id = id;
        this.book = book;
        this.reservation = reservation;
    }



    public int getId() {
        return id;
    }
    public void setId(int id) {
        this.id = id;
    }
    public Book getBook() {
        return book;
    }
    public void setBook(Book book) {
        this.book = book;
    }
    public Reservation getReservation() {
        return reservation;
    }
    public void setReservation(Reservation reservation) {
        this.reservation = reservation;
    }

    

}
